### ISSUE TITLE
installation fails on linux, missing instructions

### ISSUE THREAD

**Issue by artdgn** [antoinedc/ethernal-cli#11]
I was trying to use the hardhat plugin and to do the `login` step, but `npm install ethernal -g` fails to install. 

It seems that the issue is some library that is a prerequisite for `keytar` dependency on linux: https://github.com/atom/node-keytar#on-linux . Running the commands in the link solved the issue, so it's worth to add that to your quickstart docs and onboarding UI.

Also, the readme of this repo should be updated because it mentions `npm install ethernal-cli -g` which doesn't exist.

**Comment by antoinedc** [comment]
Hi Arthur,

Thanks for the report. I've fixed the README and will update the doc as well!

**Comment by antoinedc** [comment]
And were you able have the hardhat plugin synchronize transactions properly eventually?

**Comment by artdgn** [comment]
@antoinedc yes, thanks. 

I did have to do `npm install ethernal -g` manually to install the CLI for the `login` stage in addition to adding the plugin. It would be best if adding the plugin would also enable login without the need to manually install the CLI.

**Comment by antoinedc** [comment]
Yes, definitely, that's the plan!
I recently release a new feature ([here](https://blog.tryethernal.com/ethernal-x-alchemy-3/)), and with it each account has now an API key. I don't expose it directly yet, but it can be used to login.
I plan on integrating it in the plugin soon! I'll let you know when it's done
