### ISSUE TITLE
Strange issue after installation

### ISSUE THREAD

**Issue by typoworx-de** [antoinedc/ethernal-cli#12]
I've been installing using yarn:
```
yarn global add ethernal
```

After trying to start it (no matter with or without 'login'):
```ethernal login```

I'm getting this error:
```
~/.config/yarn/global/node_modules/ethernal/firebase.js:18
    workspace;
             ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (~/.config/yarn/global/node_modules/ethernal/bin/index.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```
Which leads to this file:
https://github.com/tryethernal/ethernal-cli/blob/6793feaf51c5fdd5dbdec23bc7f096bdc2cc0c69/firebase.js#L18

I had to comment out "workspace;" to make it work in any way. But I think the error is somewhere else?

After successfully running ```ethernal login``` (with the change in firebase.js) it obviously works. I also receive events in app.tryethernal.com dashboard. But while trying to deploy a local development smart-contract using ganache and ethernal listen the following happens:

```
Detected Truffle project ...
Getting artifact for Migrations.json in .../build/contracts
Getting artifact for Migrations.json in .../build/contracts
(node:17962) UnhandledPromiseRejectionWarning: Error: Reference.child failed: First argument was an invalid path = "/users/JVOwaZJFWZf1yOE9o2Z0AKD9Vyj2/workspaces/Ganache-CLI (127.0.0.1:8545)/contracts/0xc218f3f2f8c8c05d7debd39ac0f7bcee91dc8a20/artifact". Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]"
```

So I'm not shure is this an error in solidity smart-contract code? I've been using truffle standard template without modifications yet!

Or is it one or two different errors in ethernal-cli?

**Comment by antoinedc** [comment]
Hi!

The first error is because of your Node version I believe. Could you update to 12.9.1, please?

The second issue looks like it's because of the name of the workspace that contains invalid characters ("."). I wasn't aware of those, so I'll make sure to add some frontend validation!
In the meantime, can I change your workspace name from "Ganache-CLI (127.0.0.1:8545)", to "Ganache-CLI (localhost:8545)"? That should fix it (you can't do that on your end)

**Comment by antoinedc** [comment]
@typoworx-de, where you able to fix this with the node version?
