### ISSUE TITLE
Support for import contracts on BSC Fork

### ISSUE THREAD

**Issue by bigfootdeveloper** [antoinedc/ethernal-cli#15]
May be a new feature:

<img width="629" alt="SS" src="https://user-images.githubusercontent.com/86575184/134376271-674fa981-446d-4640-9fda-a5ea552e5ddf.png">

**Comment by antoinedc** [comment]
Yes! Definitely on the roadmap :) will update the issue once it's implemented!

**Comment by bigfootdeveloper** [comment]
Will be amazing

Thanks a lot

**Comment by antoinedc** [comment]
Hey! I've just added this feature :) go to "Settings" and there you'll see an option to set your workspace to BSC.
Once you've done that, the "Import Contract" feature will connect to BSCscan and import the ABI!

Closing this now, but feel free to reopen if you have any troubles with it!
